sylius_adyen_shop_process_notifications:
  path: /payment/adyen/{code}/notifications
  controller: sylius_adyen.controller.shop.process_notifications

sylius_adyen_localized:
  resource: "@SyliusAdyenPlugin/config/routes/shop_localized.yaml"
  prefix: /{_locale}
  requirements:
    _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

