sylius_adyen_shop_express_checkout_cart_configuration:
    path: /adyen/express-checkout/cart-configuration
    methods: [GET]
    defaults:
        _controller: sylius_adyen.controller.shop.express_checkout.cart_configuration

sylius_adyen_shop_express_checkout_google_pay_shipping_options:
    path: /adyen/express-checkout/google-pay/shipping-options
    methods: [POST]
    defaults:
        _controller: sylius_adyen.controller.shop.express_checkout.google_pay.shipping_options

sylius_adyen_shop_express_checkout_google_pay_checkout:
    path: /adyen/express-checkout/google-pay/checkout
    methods: [POST]
    defaults:
        _controller: sylius_adyen.controller.shop.express_checkout.google_pay.checkout
