imports:
  - { resource: "@SyliusAdyenPlugin/config/grids/*/*.yaml" }
  - { resource: "@SyliusAdyenPlugin/config/sylius/blocks.yml" }
  - { resource: "@SyliusAdyenPlugin/config/sylius/resources.yml" }
  - { resource: "@SyliusAdyenPlugin/config/winzou_state_machine/*.yaml" }
