sylius_resource:
    resources:
        sylius_adyen.adyen_token:
            classes:
                model: Sylius\AdyenPlugin\Entity\AdyenToken
                repository: Sylius\AdyenPlugin\Repository\AdyenTokenRepository

        sylius_adyen.adyen_reference:
            classes:
                model: Sylius\AdyenPlugin\Entity\AdyenReference
                repository: Sylius\AdyenPlugin\Repository\AdyenReferenceRepository

        sylius_adyen.log:
            driver: doctrine/orm
            classes:
                model: Sylius\AdyenPlugin\Entity\Log

        sylius_adyen.adyen_payment_detail:
            classes:
                model: Sylius\AdyenPlugin\Entity\AdyenPaymentDetail

        sylius_adyen.payment_link:
            driver: doctrine/orm
            classes:
                model: Sylius\AdyenPlugin\Entity\PaymentLink
                repository: Sylius\AdyenPlugin\Repository\PaymentLinkRepository
