sylius_resource:
  resources:
    sylius_adyen.adyen_token:
      classes:
        repository: Sylius\AdyenPlugin\Repository\AdyenTokenRepository
        model: Sylius\AdyenPlugin\Entity\AdyenToken

    sylius_adyen.adyen_reference:
      classes:
        repository: Sylius\AdyenPlugin\Repository\AdyenReferenceRepository
        model: Sylius\AdyenPlugin\Entity\AdyenReference

    sylius_adyen.log:
      driver: doctrine/orm
      classes:
        model: Sylius\AdyenPlugin\Entity\Log
