winzou_state_machine:
    sylius_payment:
        states:
            processing_reversal: ~
        transitions:
            capture:
                from: [new, processing, authorized]
                to: completed
            process:
                from: [new, authorized]
                to: processing
            cancel:
                from: [new, processing, authorized, processing_reversal]
                to: cancelled
            refund:
                from: [completed, processing_reversal]
                to: refunded
            reverse:
                from: [authorized, completed]
                to: processing_reversal
        callbacks:
            after:
                sylius_resolve_state:
                    on: ["complete", "process", "refund", "authorize", "capture"]
                auto_capture:
                    on: ["authorize"]
                    do: ["@sylius_adyen.processor.authorization_state", "process"]
                    args: ["object"]
                    priority: 100
            guard:
                guard_complete:
                    on: ["complete"]
                    do: ["@sylius_adyen.state_machine.guard.payment", "canBeCompleted"]
                    args: ["object"]
