winzou_state_machine:
    sylius_order:
        callbacks:
            after:
                # Overrides the default sylius_cancel_payment for special handling of Adyen payments
                sylius_cancel_payment:
                    on: ["cancel"]
                    do: [ "@sylius_adyen.processor.order.reverse_payment", "process" ]
                    args: [ "object" ]
                    priority: -600
