winzou_state_machine:
    sylius_order:
        callbacks:
            after:
                # Overrides the default sylius_cancel_payment for special handling of Adyen payments
                sylius_cancel_payment:
                    on: ["cancel"]
                    do: [ "@sylius_adyen.processor.order.reverse_payment", "process" ]
                    args: [ "object" ]
                    priority: -600
                cancel_authorized_payment:
                    on: ["cancel"]
                    do: [ "@sylius_adyen.callback.request_cancel", "__invoke" ]
                    args: [ "object" ]
                    priority: -500
            guard:
                cancel_with_processing_payment:
                    on: ["cancel"]
                    do: ["@sylius_adyen.state_machine.guard.order", "canBeCancelled"]
                    args: ["object"]
