winzou_state_machine:
    sylius_order_payment:
        transitions:
            pay:
                from: [awaiting_payment, partially_paid, authorized]
            cancel:
                from: [awaiting_payment, authorized, partially_authorized, paid]
        callbacks:
            guard:
                cancel_paid:
                    on: ["cancel"]
                    do: ["@sylius_adyen.state_machine.guard.order_payment", "canBeCancelled"]
                    args: ["object"]
